### ISSUE TITLE
Paper Question

### ISSUE THREAD

**Issue by AmingWu** [fmcarlucci/JigenDG#12]
I am confused about the "Deep All" setting. Could you interpret the setting clearly? Besides, does the code include the case of "Deep All"?

Thank you very much.

**Comment by fmcarlucci** [comment]
Hi, deep all simply means that the classifier is trained on the source datasets without performing the Jigsaw task and without ever seeing the target. If you use train_jigsaw and set jig_weight to 0 and bias_whole_image to 1 you should get deep all.
