### ISSUE TITLE
Questionable implementation of parsing boolean args

### ISSUE THREAD

**Issue by Gary-Shi** [fmcarlucci/JigenDG#13]
Hi, congratulations on the great work!

Although I may found something wrong with you implementation of parsing boolean args. The proper way to do that may be [https://stackoverflow.com/questions/41655897/why-is-argparse-not-parsing-my-boolean-flag-correctly](url)

**Comment by fmcarlucci** [comment]
Hi Gary, you are correct on this, thanks!
I have fixed this in bd5f1d840cfc8c0ae7d7b17ade2ab5cf28250cfd
