### ISSUE TITLE
PyTorch version of this code?

### ISSUE THREAD

**Issue by Ellenisawake** [fmcarlucci/JigenDG#18]
Hi, thanks for sharing this code as a great reference to your interesting paper.
Just a note, would you please advise the pytorch version of the code? Cause I tried run it under latest pytorch 1.4 and got series of bugs including failure of a forward pass (tensor dimension mismatch). Unfortunately the current provided requirement.txt does not give any help. Thanks!

**Comment by silvia1993** [comment]
Hi!  In "requirement.txt" line 141 you should read "torch==0.4.1", this is the correct version to run the code.
