### ISSUE TITLE
TypeError: alexnet() got an unexpected keyword argument 'jigsaw_classes'

### ISSUE THREAD

**Issue by smilesun** [fmcarlucci/JigenDG#24]
`python train_jigsaw.py --network alexnet

`> Traceback (most recent call last):
>   File "train_jigsaw.py", line 198, in <module>
>     main()
>   File "train_jigsaw.py", line 192, in main
>     trainer = Trainer(args, device)
>   File "train_jigsaw.py", line 59, in __init__
>     model = model_factory.get_network(args.network)(jigsaw_classes=args.jigsaw_n_classes + 1, classes=args.n_classes)
>   File "JigenDG/models/model_factory.py", line 21, in get_network_fn
>     return nets_map[name](**kwargs)
> TypeError: alexnet() got an unexpected keyword argument 'jigsaw_classes'

**Comment by silvia1993** [comment]
Try to use "--network caffenet"
