### ISSUE TITLE
Error with argparser

### ISSUE THREAD

**Issue by divyat09** [fmcarlucci/JigenDG#26]
I am unable to run the code using the commands from the README

I run the following commands for results on the PACS dataset:

<code> python train_jigsaw.py --batch_size 128 --n_classes 7 --learning_rate 0.001 --network resnet18 --val_size 0.1 --folder_name test --jigsaw_n_classes 30 --train_all True --TTA False --nesterov False --min_scale 0.8 --max_scale 1.0 --random_horiz_flip 0.5 --jitter 0.4 --tile_random_grayscale 0.1 --source photo cartoon sketch --target art_painting --jig_weight 0.7 --bias_whole_image 0.9 --image_size 222 </code>

However, it results in the following error:

Traceback (most recent call last):
  File "train_jigsaw.py", line 199, in <module>
    main()
  File "train_jigsaw.py", line 191, in main
    args = get_args()
  File "train_jigsaw.py", line 43, in get_args
    parser.add_argument("--TTA", type=bool, action='store_true', help="Activate test time data augmentation")
  File "/anaconda/envs/py37_default/lib/python3.7/argparse.py", line 1359, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'type'

**Comment by silvia1993** [comment]
True or False is not required for "--TTA" since it is defined with _action='store_true'_

If you don't want to use it, don't add it.
"--TTA" means "--TTA True"
"" means "--TTA False"

**Comment by divyat09** [comment]
Thanks, I think this should be updated in the main code in the repo too.

**Comment by talhazaidi131313** [comment]
Hi 
I am getting the same issue, I tried it without adding --TTA False in the run command but still getting the same error. can you tell how you resolved it?
