### ISSUE TITLE
Office home dataset

### ISSUE THREAD

**Issue by talhazaidi131313** [fmcarlucci/JigenDG#29]
Hi,
 I am trying to run your code to generate the results for the office home dataset, which you referred in table 3.  I found out that the dataset txt files present in the code folders are for the office dataset (30classes, 3 domains) instead of the office home dataset (65 classes, 4 domains) which is reported in table 3.  So I uploaded the Office home dataset with its generated txt files and loaded in the code. However, while running I am getting the following runtime error:

{
JigenDG-master/train_DA_jigsaw.py in _do_epoch(self)
    107             loss = class_loss + jigsaw_loss * self.jig_weight + target_jigsaw_loss * self.target_weight + target_entropy_loss * self.target_entropy
    108 
--> 109             loss.backward()

RuntimeError: cuda runtime error (710) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCTensorMath.cu:29
}

I used the following initial parameters:

%run train_jigsaw.py --batch_size 128 --n_classes 65 --learning_rate 0.001 --network resnet18 --val_size 0.1 --folder_name test --jigsaw_n_classes 100 --train_all True --TTA False --nesterov False --min_scale 0.8 --max_scale 1.0 --random_horiz_flip 0.5 --jitter 0.4 --tile_random_grayscale 0.1 --source Art Clipart Real_World --target Product --jig_weight 0.7 --bias_whole_image 0.9 --image_size 222

Can you please guide me that, if I am making any mistake while selecting the initial parameters?

thank you

**Comment by silvia1993** [comment]
Hi @talhazaidi131313 ,

are you sure that the labels in your office-home txt files are between 0 and 64?

**Comment by talhazaidi131313** [comment]
Hello,
   Thank you for your reply. I was using the labels between 1 and 65. I corrected it and now it is working. 
Thank you.

**Comment by zdhNarsil** [comment]
@talhazaidi131313 I wonder how can I download officehome dataset?

**Comment by silvia1993** [comment]
Hi @zdhNarsil,
you can download the Office-Home dataset here: 
[https://drive.google.com/file/d/0B81rNlvomiwed0V1YUxQdC1uOTg/view](url)
