### ISSUE TITLE
Why is the input data composed with 9 grid?

### ISSUE THREAD

**Issue by anjaeju** [fmcarlucci/JigenDG#31]
![image](https://user-images.githubusercontent.com/40862925/96845114-4c6aa800-148b-11eb-8a24-6759839be1d4.png)

I tried to plot the input data for understanding as expecting that 222 x 222 x 3 one original or jigsaw(permutated) image.
But the result is composed with 9-grid patched image.
I don't understand why the input data looks like it, cuz i cannot find this information in the paper

**Comment by fmcarlucci** [comment]
Hello, that is not the intended behavior. Can you share the code you used to produce those images?

**Comment by anjaeju** [comment]
Maybe I treat the code wrongly
