### ISSUE TITLE
evaluate on VLCS dataset

### ISSUE THREAD

**Issue by GA-17a** [fmcarlucci/JigenDG#46]
Hi,
According to your code, do you train your model on 3 source domains(90% full as training dataset) and chose the model with highest accuracy on 3 source domains(10% full as validation dataset) to report the result on target domain(only on test dataset)?

**Comment by silvia1993** [comment]
Hi @GA-17a,

yes it is correct!

**Comment by GA-17a** [comment]
Got it. Thanks for your reply!

**Comment by GA-17a** [comment]
Hi  @silvia1993,
I also have another question. Just like PACS dataset, why don't you think about reporting the result on target domain(on the whole dataset: full+test)?

**Comment by silvia1993** [comment]
Hi @GA-17a,

we report these results for VLCS dataset because the methods with which we compare use these same splits.

**Comment by GA-17a** [comment]
Thanks for your reply!
